[application]

[bundle]
identifier = "com.wheregmis.blinkion"
publisher = "wheregmis"
icon = ["assets/icon.png"]

[web.app]

# HTML title tag content
title = "blinkion"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
